<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	"[DASHBOARD] Chart nameTotal net earnings from vendors" => array(
		_x( "Total net earnings from vendors", "[DASHBOARD] Chart name", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Chart nameTotal earnings from vendors" => array(
		_x( "Total earnings from vendors", "[DASHBOARD] Chart name", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Chart nameOrders" => array(
		_x( "Orders", "[DASHBOARD] Chart name", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Chart nameCommissions" => array(
		_x( "Commissions", "[DASHBOARD] Chart name", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Chart nameTotal commissions" => array(
		_x( "Total commissions", "[DASHBOARD] Chart name", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Chart namePending commissions" => array(
		_x( "Pending commissions", "[DASHBOARD] Chart name", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Chart namePaid commissions" => array(
		_x( "Paid commissions", "[DASHBOARD] Chart name", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Chart nameRefunded commissions" => array(
		_x( "Refunded commissions", "[DASHBOARD] Chart name", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] FiltersShow" => array(
		_x( "Show", "[DASHBOARD] Filters", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] FiltersAll vendors" => array(
		_x( "All vendors", "[DASHBOARD] Filters", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] FiltersSingle vendor" => array(
		_x( "Single vendor", "[DASHBOARD] Filters", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] FiltersSearch for a vendor" => array(
		_x( "Search for a vendor", "[DASHBOARD] Filters", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] FiltersComparison" => array(
		_x( "Comparison", "[DASHBOARD] Filters", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] FiltersSelect at least two vendors to compare" => array(
		_x( "Select at least two vendors to compare", "[DASHBOARD] Filters", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] FiltersSearch for vendors to compare" => array(
		_x( "Search for vendors to compare", "[DASHBOARD] Filters", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] FiltersCompare vendors" => array(
		_x( "Compare vendors", "[DASHBOARD] Filters", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] FiltersCompare" => array(
		_x( "Compare", "[DASHBOARD] Filters", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Time diffy" => array(
		_x( "y", "[DASHBOARD] Time diff", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Time diffmo" => array(
		_x( "mo", "[DASHBOARD] Time diff", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Time diffw" => array(
		_x( "w", "[DASHBOARD] Time diff", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Time diffd" => array(
		_x( "d", "[DASHBOARD] Time diff", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Time diffh" => array(
		_x( "h", "[DASHBOARD] Time diff", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Time diffm" => array(
		_x( "m", "[DASHBOARD] Time diff", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Time diffs" => array(
		_x( "s", "[DASHBOARD] Time diff", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Empty chart messageNo data available" => array(
		_x( "No data available", "[DASHBOARD] Empty chart message", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Products leaderboardTop products" => array(
		_x( "Top products", "[DASHBOARD] Products leaderboard", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Products leaderboardProduct" => array(
		_x( "Product", "[DASHBOARD] Products leaderboard", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Products leaderboardTotal commissions" => array(
		_x( "Total commissions", "[DASHBOARD] Products leaderboard", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Products leaderboardEarnings generated" => array(
		_x( "Earnings generated", "[DASHBOARD] Products leaderboard", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Vendors leaderboardTop vendors" => array(
		_x( "Top vendors", "[DASHBOARD] Vendors leaderboard", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Vendors leaderboardVendor" => array(
		_x( "Vendor", "[DASHBOARD] Vendors leaderboard", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Vendors leaderboardTotal commissions" => array(
		_x( "Total commissions", "[DASHBOARD] Vendors leaderboard", 'yith-woocommerce-product-vendors' ),
	),
	"[DASHBOARD] Vendors leaderboardEarnings generated" => array(
		_x( "Earnings generated", "[DASHBOARD] Vendors leaderboard", 'yith-woocommerce-product-vendors' ),
	),
);